generator/urls.py
from django.urls import path
from . import views

app_name= 'generator'

urlpatterns = [
    path('', views.generator, name='generatePage'),
    path('password', views.password, name='passPage')
]

passwordGenerator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('generator.urls')),
    path('admin/', admin.site.urls),
]

generator/models.py
from django.db import models

# Create your models here.

generator/views.py
from django.shortcuts import render, redirect
import string, random

def generator(request):
    return render(request, 'generatorPage.html')

def password(request):
    if request.method == 'POST':
        characters=[]
        length= request.POST.get('passLength')
        if request.POST.get('upperChar'): 
            characters.extend(list(string.ascii_uppercase))
        if request.POST.get('lowerChar'): 
            characters.extend(list(string.ascii_lowercase))
        if request.POST.get('digits'): 
            characters.extend(list(string.digits))
        generatedPass= ''.join(random.choices(
            characters,
            k= int(length)))
        return render(request, 'password.html', {'password': generatedPass})
    return render(request, 'password.html')

generator/templates/generatorPage.html
{% extends 'mainTemplate.html' %}
    {% block content%}
        <form action="{% url 'generator:passPage'%}" method="post">
            {% csrf_token %}
            <label for="passLength">Length
            <select name="passLength" id="passLength">
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
                <option value="11">11</option>
                <option value="12">12</option>
            </select></label>
            <label for="upperChar">Uppercase letter
                <input type="checkbox" name="upperChar" id="upperChar"></label>
            <label for="lowerChar">Lowercase letter
                <input checked type="checkbox" name="lowerChar" id="lowerChar"></label>
            <label for="digits">Digits
                <input type="checkbox" name="digits" id="digits"></label>
            <button type="submit">Generate</button>
        </form>
    {% endblock%}

generator/templates/password.html
{% extends 'mainTemplate.html' %}
    {% block content%}
        <h3>Your Password</h3>
        <div id="password">
            {{password}}
        </div>
        <a href="{% url 'generator:generatePage' %}">Home</a>
    {% endblock %}

templates/mainTemplate.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{%static 'styles.css'%}">
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    <nav>Password Generator</nav>
    {% block content%}
    {% endblock%}
</body>
</html>